name: Context
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PASSWORD : ${{secrets.PASSWORD}}
    steps:
      - run: echo "${{github.actor_id}}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
