name: Generate functions
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{fortmat('{0}, {1}.', 'Hi', 'world')}}
          JOIN_FUNC: ${{join(github.event.*.html_url), ','}}
